---
batting_styles:
- key: ＤＢ
  name: ＤＢ
  description: 死球
- key: けが
  name: けが
  description: 負傷チェックを行う。日数が指定されている場合はその日数負傷する。
- key: １Ｃ５
  name: １Ｃ５
  description: 走者がいる場合は投球ナンバー５、いる場合は投球ナンバー１として打ち直し
- key: チャンス
  name: チャンス
  description: 走者がいる場合は投球ナンバー１、いる場合は投球ナンバー５として打ち直し
- key: 内野安打
  name: 内野安打
  description: 内野安打を打つ。ただし、１塁走者がいれば２塁フォースアウト、前進守備なら３塁走者がタッチアウトになる。
- key: 対左
  name: 対左
  description: 右投手に対しては投球ナンバー５、左投手に対しては投球ナンバー１として打ち直し
- key: 対右
  name: 対右
  description: 右投手に対しては投球ナンバー１、左投手に対しては投球ナンバー５として打ち直し
