---
pitching_skills:
- key: ＷＰしない
  name: ＷＰしない
  description: あらゆる暴投を防ぐ。捕逸は防げない
  skill_type: positive
- key: ボークしない
  name: ボークしない
  description: ボークを防ぐ。
  skill_type: positive
- key: 精神疲労
  name: 精神疲労
  description: 失点すると疲労状態になる。
  skill_type: negative
- key: クイック○
  name: クイック○
  description: 登板中に盗塁されたとき、盗塁のst値が+2され、捕手のT値が+2される。
  skill_type: positive
- key: クイック×
  name: クイック×
  description: 登板中に盗塁されたとき、盗塁のst値が-2され、捕手のT値が-2される。
  skill_type: negative
- key: 牽制○
  name: 牽制○
  description: 盗塁スタート時に出目20が出たとき、その走者を確定でアウトにする。
  skill_type: positive
- key: 暴投追加
  name: 暴投追加
  description: ２死以外で投球ナンバー５、打撃出目１９で三振になったとき、暴投として走者が１進塁する。
  skill_type: negative
- key: 代打可
  name: 代打可
  description: 通常投手は代打起用できないが、代打可の選手は代打で出場できる。
  skill_type: neutral
- key: オープナー
  name: オープナー
  description: オープナーとして起用できる。
  skill_type: neutral
- key: バイオリズム
  name: バイオリズム
  description: 試合日が指定期間内のときに投手特徴が出た場合、投球ナンバー５で振り直す（一部選手は効果が異なる）
  skill_type: neutral
- key: クローザー
  name: クローザー
  description: 9回以降にしか登板できない
  skill_type: neutral
- key: 要中10日
  name: 要中10日
  description: １回登板すると、１０日空けないと次の登板ができない
  skill_type: negative
- key: １イニング限定
  name: １イニング限定
  description: 回またぎができない
  skill_type: neutral
- key: 登板前後出場不可
  name: 登板前後出場不可
  description: 登板する前日と翌日には打者含め出場できない
  skill_type: neutral
