---
player_types:
- key: 東方
  name: 東方
  description: 東方キャラ。このゲームの中心となる選手。
  category: touhou
- key: ハチナイ
  name: ハチナイ
  description: ハチナイコラボで使用可能になった選手
  category: outside_world
- key: 球詠
  name: 球詠
  description: 球詠コラボで使用可能になった選手
  category: outside_world
- key: ＰＭ
  name: ＰＭ
  description: プレイングマネージャー。IRCである程度遊ぶと作成されることがある
  category: outside_world
- key: ＡＰ
  name: ＡＰ
  description: 毎年エイプリルフールに作成されることがあるネタカード。公式化されることもある
  category: outside_world
- key: オリジナル
  name: オリジナル
  description: ペナントを１シーズン完了させた記念に作成されたカード
  category: outside_world
- key: 横綱
  name: 横綱
  description: 伝説の戦犯として、ファンサービスを兼ねて作成された記念カード（公式戦使用不可）
  category: outside_world
- key: 二刀流
  name: 二刀流
  description: 投手・野手の両方で出場できる選手。どちらかに専念することもできる
  category: cost_regulation
- key: リリーフ契約可
  name: リリーフ契約可
  description: リリーフ専任になる代わりに低コストで契約できる
  category: cost_regulation
